pipeline {
   agent any

   stages {
       stage('Clone') {
            steps {
                echo "checking out the repo"
                git 'https://github.com/smaji512/jenkins-demo.git'
            
            }
        }
        stage('build'){
            steps {
                echo "building the project"
                sh "cd MavenProject ; mvn clean install ; pwd"
            }
        }
        
        stage('Archieve Artifacts'){
            steps {
                echo "archiving the artifacts"
                archiveArtifacts 'MavenProject/multi3/target/*.war'
            }
            
        }
        stage('Deployment') {
            // Deployment
            steps {
                script {
                    echo "deployment"
                    sh 'cp MavenProject/multi3/target/*.war /opt/tomcat/apache-tomcat-8.5.50/webapps/'
                }
            }
        }
        
    
    }
    post {
            always{
               emailext body: 'Successfully completed pipeline project with archiving the artifacts and deploying the war file', subject: 'Pipeline was successfull', to: 'subrath.maji@gmail.com' 
            }
    }
}

